const mongoose = require("mongoose");

const adminProductSchema = new mongoose.Schema({
  name:{
    type:String,
    required:true
  },
  category:{
    type:String,
    required:true,
  },
  product_code:{
    type:String,
    required:true,
  },
  weight:{
    type:String,
    required:false,
  },
  length:{
    type:String,
    required:false,
  },
  diameter:{
    type:String,
    required:false,
  },
  material:{
    type:String,
    required:false
  },
  color:{
    type:String,
    requiredd:true,
  },
  price:{
    type:Number,
    required:true,
  },
  stocks:{
    type:Number,
    required:false,
  },
  description:{
    type:String,
    required:false,
  },
  available:{
    type:Boolean,
    required:true,
    default:false,
  },
  adminId:{
    type:String,
    required:true,
  },
  img:{
    type:String,
    required:true,
  },
  createdAt:{
    type:Date,
    default:Date.now,
  }
});
const adminProduct = mongoose.model("adminProduct", adminProductSchema);
module.exports = adminProduct;